#!/bin/sh
# Invoke Qwen Code CLI headlessly for cross-provider envoy.
# Exit: 0=success, 1=invocation failed, 2=interrupted (provider-specific), 3=output validation failed

set -eu
umask 077

error() { printf 'Error: %s\n' "$*" >&2; }

usage() {
    cat <<'EOF'
Usage: invoke-qwen.sh --prompt-file PATH --output-file PATH --stderr-log PATH [--tier frontier|standard|fast]

Invoke Qwen Code CLI headlessly with sanitized environment.
EOF
}

# --- Argument parsing ---

prompt_file="" output_file="" stderr_log="" tier="standard" fallback_for=""

while [ $# -gt 0 ]; do
    case "$1" in
        --prompt-file)  prompt_file="$2"; shift 2 ;;
        --output-file)  output_file="$2"; shift 2 ;;
        --stderr-log)   stderr_log="$2"; shift 2 ;;
        --tier)         tier="$2"; shift 2 ;;
        --fallback-for) fallback_for="$2"; shift 2 ;;
        -h|--help)      usage; exit 0 ;;
        *)              error "Unknown argument: $1"; usage; exit 1 ;;
    esac
done

[ -n "$prompt_file" ]  || { error "Missing --prompt-file"; usage; exit 1; }
[ -n "$output_file" ]  || { error "Missing --output-file"; usage; exit 1; }
[ -n "$stderr_log" ]   || { error "Missing --stderr-log"; usage; exit 1; }
[ -f "$prompt_file" ]  || { error "Prompt file not found: $prompt_file"; exit 1; }
[ -s "$prompt_file" ]  || { error "Prompt file is empty: $prompt_file"; exit 1; }

# --- Shared functions ---

_script_dir=$(cd "$(dirname "$0")" && pwd)
# shellcheck source=_common.sh
. "$_script_dir/_common.sh"

command -v jq >/dev/null 2>&1 || { error "jq required but not found"; exit 1; }

# --- Tier-aware model selection (configurable via SPINE_ENVOY_{TIER_}QWEN=model) ---
# Qwen has no effort parameter; env var overrides are model-only (no :effort suffix).

resolve_tier "$tier" qwen
case "$tier" in
    frontier) model="${SPINE_ENVOY_FRONTIER_QWEN:-${SPINE_ENVOY_QWEN:-$_tier_model}}" ;;
    fast)     model="${SPINE_ENVOY_FAST_QWEN:-${SPINE_ENVOY_QWEN:-$_tier_model}}" ;;
    *)        model="${SPINE_ENVOY_STANDARD_QWEN:-${SPINE_ENVOY_QWEN:-$_tier_model}}" ;;
esac
_qwen_timeout=3600  # liveness safety net

# --- Pre-flight + cleanup ---

preflight_check
init_cleanup

# --- Invoke (stdin pipe bypasses ARG_MAX; no --yolo — envoy is review-only) ---

_json_tmp="${output_file}.json"
start_timer

printf 'envoy: invoking qwen (model=%s)...\n' "$model" >&2
_rc=0
timeout --kill-after=10 "$_qwen_timeout" env \
    -u CLAUDECODE -u CURSOR_AGENT -u CODEX_SANDBOX \
    -u QWEN_CODE -u QWEN_CODE_NO_RELAUNCH \
    PATH="$HOME/.local/bin:$PATH" \
    qwen -p \
        --model "$model" \
        --output-format json \
        < "$prompt_file" \
        > "$_json_tmp" 2>"$stderr_log" \
    || _rc=$?

printf 'envoy: qwen completed (exit=%s), validating...\n' "$_rc" >&2
# Defer _cleanup until after JSON extraction — _cleanup deletes $_json_tmp
if [ "$_rc" -eq 124 ] || [ "$_rc" -eq 137 ]; then
    _cleanup
    error "Qwen CLI timed out after ${_qwen_timeout}s"; exit 2
fi
handle_exit_code "Qwen CLI"
stop_timer

# --- Extract body and metadata from JSON array output ---
# Qwen outputs a JSON array; the final element has type "result" with .result field.
# Init element (.[0]) has session_id and model. Result element (.[-1]) has duration_ms.

if [ -f "$_json_tmp" ] && jq -e '.[-1].result' "$_json_tmp" >/dev/null 2>&1; then
    jq -r '.[-1].result // ""' "$_json_tmp" > "$output_file"
    _meta_session_id=$(jq -r '.[0].session_id // "none"' "$_json_tmp")
    _duration_ms=$(jq -r '.[-1].duration_ms // empty' "$_json_tmp")
    _meta_resolved_model=$(jq -r '.[0].model // empty' "$_json_tmp")
else
    _cleanup
    error "JSON extraction failed from Qwen output"
    exit 3
fi
rm -f "$_json_tmp"
_json_tmp=""
_cleanup

# Prefer API-reported duration if available, otherwise shell timing
_meta_elapsed="${_duration_ms:+$(( _duration_ms / 1000 ))}"
_meta_elapsed="${_meta_elapsed:-$_timer_elapsed}"

# --- Validate + sanitize + trust-boundary marker ---

validate_output

_meta_provider="Qwen Code"
_meta_model="$model"
_meta_effort=""
_meta_fallback_note=""
if [ -n "$fallback_for" ]; then
    _meta_provider="$fallback_for -> Qwen Code Fallback"
    _meta_fallback_note="Note: $fallback_for was unavailable. This response was generated by Qwen Code as fallback."
fi

assemble_output
finalize_output
