#!/bin/sh
# Invoke MiniMax via OpenCode CLI headlessly for cross-provider envoy.
# Exit: 0=success, 1=invocation failed, 2=interrupted (provider-specific), 3=output validation failed

set -eu
umask 077

error() { printf 'Error: %s\n' "$*" >&2; }

usage() {
    cat <<'EOF'
Usage: invoke-minimax.sh --prompt-file PATH --output-file PATH --stderr-log PATH [--tier frontier|standard|fast]

Invoke MiniMax via OpenCode CLI headlessly with sanitized environment.
EOF
}

# --- Argument parsing ---

prompt_file="" output_file="" stderr_log="" tier="standard" fallback_for=""

while [ $# -gt 0 ]; do
    case "$1" in
        --prompt-file)  prompt_file="$2"; shift 2 ;;
        --output-file)  output_file="$2"; shift 2 ;;
        --stderr-log)   stderr_log="$2"; shift 2 ;;
        --tier)         tier="$2"; shift 2 ;;
        --fallback-for) fallback_for="$2"; shift 2 ;;
        -h|--help)      usage; exit 0 ;;
        *)              error "Unknown argument: $1"; usage; exit 1 ;;
    esac
done

[ -n "$prompt_file" ]  || { error "Missing --prompt-file"; usage; exit 1; }
[ -n "$output_file" ]  || { error "Missing --output-file"; usage; exit 1; }
[ -n "$stderr_log" ]   || { error "Missing --stderr-log"; usage; exit 1; }
[ -f "$prompt_file" ]  || { error "Prompt file not found: $prompt_file"; exit 1; }
[ -s "$prompt_file" ]  || { error "Prompt file is empty: $prompt_file"; exit 1; }

# --- Shared functions ---

_script_dir=$(cd "$(dirname "$0")" && pwd)
# shellcheck source=_common.sh
. "$_script_dir/_common.sh"
# shellcheck source=_opencode-common.sh
. "$_script_dir/_opencode-common.sh"

command -v jq >/dev/null 2>&1 || { error "jq required but not found"; exit 1; }

# --- Tier-aware model selection (configurable via SPINE_ENVOY_{TIER_}MINIMAX=model:effort) ---

resolve_tier "$tier" minimax
case "$tier" in
    frontier) _envoy_val="${SPINE_ENVOY_FRONTIER_MINIMAX:-${SPINE_ENVOY_MINIMAX:-$_tier_model:$_tier_effort}}" ;;
    fast)     _envoy_val="${SPINE_ENVOY_FAST_MINIMAX:-${SPINE_ENVOY_MINIMAX:-$_tier_model:$_tier_effort}}" ;;
    *)        _envoy_val="${SPINE_ENVOY_STANDARD_MINIMAX:-${SPINE_ENVOY_MINIMAX:-$_tier_model:$_tier_effort}}" ;;
esac
model="${_envoy_val%%:*}"
effort="${_envoy_val#*:}"
[ "$effort" = "$model" ] && effort=high

# --- Pre-flight + cleanup ---

preflight_check
init_cleanup

# --- Invoke via OpenCode shared transport ---

opencode_invoke "$model" "$effort"

# Defer _cleanup until after extraction — _cleanup deletes $_json_tmp
# shellcheck disable=SC2154  # _rc, _opencode_timeout set by opencode_invoke / _opencode-common.sh
if [ "$_rc" -eq 124 ] || [ "$_rc" -eq 137 ]; then
    _cleanup
    error "OpenCode CLI timed out after ${_opencode_timeout}s"; exit 2
fi
handle_exit_code "OpenCode CLI (MiniMax)"
stop_timer

# --- Extract body and metadata from JSONL output ---

opencode_extract

# --- Validate + sanitize + trust-boundary marker ---

validate_output

_meta_provider="MiniMax"
_meta_model="$model"
_meta_effort="$effort"
_meta_fallback_note=""
if [ -n "$fallback_for" ]; then
    _meta_provider="MiniMax (fallback for $fallback_for)"
    _meta_fallback_note="Note: $fallback_for was unavailable. This response was generated by MiniMax as fallback."
fi

assemble_output
finalize_output
