#!/usr/bin/env bash
# Count tokens for all AI-loaded files and maintain a YAML manifest.
#
# Usage:
#   scripts/token-counts.sh            # check for drift against manifest
#   scripts/token-counts.sh --update   # regenerate manifest with current counts

set -euo pipefail

REPO_ROOT="$(git -C "$(dirname "$0")" rev-parse --show-toplevel)"
MANIFEST="$REPO_ROOT/token-counts.yaml"
MODEL="gpt-4.1"

# --- Auto-install tokenizer if missing ---

ensure_tokenizer() {
  command -v tokenizer &>/dev/null && return
  echo "tokenizer not found — installing via Homebrew..."
  if ! command -v brew &>/dev/null; then
    echo "Error: tokenizer is required but Homebrew is not available." >&2
    echo "Install manually: brew install zahidcakici/tap/tokenizer" >&2
    exit 1
  fi
  brew install zahidcakici/tap/tokenizer
}

# --- File discovery ---

discover_files() {
  cd "$REPO_ROOT"
  {
    # Root files
    echo "SPINE.md"
    # Agent files
    printf '%s\n' agents/*.md
    # Skill files + references
    printf '%s\n' skills/*/SKILL.md
    for dir in skills/*/references; do
      [ -d "$dir" ] && printf '%s\n' "$dir"/*.md
    done
    # Claude plugin skills + agents
    for dir in claude/skills/*/; do
      [ -f "${dir}SKILL.md" ] && echo "${dir}SKILL.md"
    done
    for f in claude/agents/**/*.md; do
      [ -f "$f" ] && echo "$f"
    done
  } | sort -u
}

# --- Token counting ---

count_tokens() {
  local file="$1"
  tokenizer -f "$file" -m "$MODEL" 2>/dev/null \
    | sed -n 's/.*Tokens:[[:space:]]*\([0-9]*\).*/\1/p'
}

# --- Manifest I/O ---

generate_manifest() {
  cd "$REPO_ROOT"
  {
    echo "# token-counts.yaml - o200k_base ($MODEL)"
    echo "# Generated by: scripts/token-counts.sh --update"
    while IFS= read -r file; do
      tokens="$(count_tokens "$file")"
      if [ -z "$tokens" ]; then
        echo "Warning: could not count tokens for $file" >&2
        continue
      fi
      echo "$file: $tokens"
    done < <(discover_files)
  }
}

# --- Modes ---

do_update() {
  ensure_tokenizer
  generate_manifest > "$MANIFEST"
  echo "Updated $MANIFEST"
}

do_check() {
  ensure_tokenizer

  if [ ! -f "$MANIFEST" ]; then
    echo "No manifest found at $MANIFEST" >&2
    echo "Run: scripts/token-counts.sh --update" >&2
    exit 1
  fi

  # Generate fresh counts to a temp file, diff against committed manifest
  CHECK_TMP="$(mktemp)"
  trap 'rm -f "$CHECK_TMP"' EXIT
  generate_manifest > "$CHECK_TMP"

  # Strip comments for comparison
  local old_data=""
  old_data="$(grep -v '^#' "$MANIFEST" | grep -v '^$' | sort)"
  local new_data=""
  new_data="$(grep -v '^#' "$CHECK_TMP" | grep -v '^$' | sort)"

  if [ "$old_data" = "$new_data" ]; then
    return 0
  fi

  # Show human-readable diff
  local changes=0
  while IFS= read -r line; do
    case "$line" in
      "< "*)
        # In old but not new (removed) or old value (changed)
        entry="${line#< }"
        path="${entry%%:*}"
        old_count="${entry##*: }"
        new_line="$(echo "$new_data" | grep "^${path}:" || true)"
        if [ -z "$new_line" ]; then
          echo "  removed: $path"
        else
          new_count="${new_line##*: }"
          echo "  changed: $path  $old_count -> $new_count"
        fi
        changes=$((changes + 1))
        ;;
      "> "*)
        # In new but not old (added)
        entry="${line#> }"
        path="${entry%%:*}"
        old_line="$(echo "$old_data" | grep "^${path}:" || true)"
        if [ -z "$old_line" ]; then
          count="${entry##*: }"
          echo "  added:   $path  $count"
          changes=$((changes + 1))
        fi
        ;;
    esac
  done < <(diff <(echo "$old_data") <(echo "$new_data") || true)

  if [ "$changes" -gt 0 ]; then
    echo ""
    echo "$changes file(s) differ from manifest."
    echo "Run: scripts/token-counts.sh --update"
    exit 1
  fi
}

# --- Main ---

case "${1:-}" in
  --update) do_update ;;
  --help|-h)
    sed -n '2,/^$/s/^# //p' "$0"
    ;;
  "") do_check ;;
  *)
    echo "Unknown option: $1" >&2
    echo "Usage: scripts/token-counts.sh [--update]" >&2
    exit 1
    ;;
esac
